{{- include "adp-helm-library.deployment" (list . "adp-backend-template-node.deployment") -}}
{{- define "adp-backend-template-node.deployment" -}}
spec:
  template:
    spec:
      containers:
      - {{ include "adp-helm-library.container" (list . "adp-backend-template-node.container") }}
{{- end -}}
